Add exclusion rule support for urls
defunctzombie/node-taters pull request #4
Opened 2016-11-12 00:33 UTC by theogravity

2016-11-12 02:08 UTC, defunctzombie commented
Add a test for this please

2016-11-12 02:58 UTC, theogravity commented
@defunctzombie  added, it seems that the 0.8 node install is failing on the CI though, seems to be independent of my changes

2016-11-12 18:41 UTC, defunctzombie requested changes

2016-11-12 18:41 UTC, defunctzombie commented on lib/fingerprint.js
> +            excluded = opt.exclude.some(function (rule) {
does this function need to be created inside of every onnode call?

2016-11-12 18:41 UTC, defunctzombie commented on lib/fingerprint.js
> +        if (excluded) {
You don't need this if statement again here and can just check excluded above in the previous if

2016-11-12 18:41 UTC, defunctzombie commented on lib/fingerprint.js
> +            excluded = opt.exclude.some(function (rule) {
This can be `const` if you remove the if statement below

2016-11-12 18:41 UTC, defunctzombie commented
Thanks for adding the tests. I made some comments on the PR. You can ignore the failure for 0.8 as I will just remove that altogether from travis and update the versions this is tested on.

2016-11-14 08:33 UTC, theogravity commented on lib/fingerprint.js
> +            excluded = opt.exclude.some(function (rule) {
it does, it depends on `orig` from line 59.

Unless you'd like me to move the function to a higher level and bind `orig` to the context.

2016-11-14 16:15 UTC, defunctzombie approved these changes

2016-11-14 16:16 UTC, merged